name: build-all
on:
  workflow_dispatch: # allow manually triggering builds
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore: # don't rebuild on documentation change
      - '**.md'
  schedule:
    - cron: '0 0 * * TUE'

#env:
#    IMAGE_TAGS: latest
#    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build_base_images:
    name: Build and push base images
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        build:
          - containerfile: fedora-rpmfusion-toolbox
          - containerfile: cosign-toolbox
          - containerfile: calibre-toolbox
          - containerfile: signal-toolbox
    uses: ./.github/workflows/build-image.yml
    with:
      event_name: ${{ github.event_name }}
      containerfile: ${{ matrix.build.containerfile }}
      image_name: ${{ matrix.build.containerfile }}
      image_tags: ${{ github.event_name != 'pull_request' && 'latest' || 'testing' }}
      large_image: true
    secrets: inherit

  build_dev_images:
    needs:
      - build_base_images
    name: Build and push dev images
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        build:
          - containerfile: fedora-dev-toolbox
            large_image: true
# Disabled, too big for github actions (~28 GB, but requires more than double that during build)
#          - containerfile: fedora-ide-toolbox
#            large_image: true
    uses: ./.github/workflows/build-image.yml
    with:
      event_name: ${{ github.event_name }}
      containerfile: ${{ matrix.build.containerfile }}
      image_name: ${{ matrix.build.containerfile }}
      image_tags: ${{ github.event_name != 'pull_request' && 'latest' || 'testing' }}
      base_image_tag: ${{ github.event_name != 'pull_request' && 'latest' || 'testing' }}
      large_image: ${{ matrix.build.large_image }}
    secrets: inherit
